### ISSUE TITLE
Include of non-modular header inside framework

### ISSUE THREAD

**Issue by ReFiRnE** [situscale/iOS-SDK#2]
I am using cocoapods 1.0.4 and getting this error.
Tried CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = 'YES', didn't helped me.

**Comment by glub** [comment]
@ReFiRnE We're having some issues getting the cocoapod working. The part I can't figure out is how to specify that we are delivering it as a dynamic framework (no source code). For now, the best option is to just pull the SITUBluetooth.framework directly into your app (unless you can point me to the docs on how to setup the podspec to reference the framework properly).

**Comment by glub** [comment]
@ReFiRnE The cocoapods workflow should be working again.
