### ISSUE TITLE
unrecognised selector .scaleDisconnected

### ISSUE THREAD

**Issue by simplyira** [situscale/iOS-SDK#3]
We implemented the SITU SDK in our project - using the sample swift project as an example. We are unable to pair the device, nor scan for it from any iOS device. Android devices are sensing it.

**Comment by glub** [comment]
@simplyira I'll take a look at what is going wrong. Thanks.

**Comment by simplyira** [comment]
It just worked with the barebones sample project. Sorry, the one we had earlier was the sample project files added to our own project and wired up to a view. We still can't pair, but with the barebones sample project, it seems it doesn't need to be paired to receive data. Sorry for the trouble! We will test tonight and update.

**Comment by glub** [comment]
@simplyira Best news ever. Thanks for letting me know!
